### ISSUE TITLE
Over 700 unknown iBeacon entries and counting from out of nowhere.

### ISSUE THREAD

**Issue by Musicman50** [custom-components/ble_monitor#1045]
Hey Folks..
I've tried everything here to get this from happening.
I keep getting an Apple iBeacon device that keeps populating daily and now counting to over 700 entities.
Also to clarify, these are not just events, but more like new devices showing up.? (At least I think)
I don't known an Apple or an iBeacon. I've tried deleting, but can't only disable, but they keep coming back.
I do have multiple Xaiomi ATC Bluetooth thermometers and a couple other devices that show up and work flawlessly. 
Can someone explain why and how I can fix this?
If Yaml programming please be kindly descriptive as I've not needed to use it or know how to.
Thanks so very much

Information from just one of many...
Device:
sensor.ble_cypress_temperature_0438bxxxad01f1571e4290d5507xxxx
Manufacturer:
Apple
Model:
iBeacon

**Comment by Ernst79** [comment]
Not sure why you get so many devices, but you can disable automatic discovery in the ble monitor settings

**Comment by Musicman50** [comment]
Well I considered that, but it defeats a feature of the program.
What I need to know is Why? and how to resolve the problem.

**Comment by Ernst79** [comment]
My thirst guess is that it is some cheap device that has misused the Apple iBeacon  format, but is using the uuid to send the data. Each datachange will add a new device. However, it’s the first time I hear this. Can you post a screenshot of some devices. Are these uuids allmost the same, or completely different.

**Comment by Musicman50** [comment]
I posted one of the devices in my very first post.
**At This Point it's serious. CAN SOMEONE PLEASE PLEASE HELP.**
**I'VE NOW GOT OVER 700 Bluetooth devices and more each day (In Reality only have 7 devices. 5 Xiomai and 2 other BT devices)**
This can't be "Rocket Science" How can I just delete these stealth devices???? And If it's in YAML then please tell me how before my whole system crashes...
I've only received an idea from one person. 
**HELP HELP HELP SOS !!!**

Just one device here.. I've got over 700 more "Unknown Apple iBeacon devices if you want them..
Information from just one of many... Don;t know how or why they are here. I only have 7 devices total, but HA says I have 700 as of today. 
Device:
sensor.ble_cypress_temperature_0438bxxxad01f1571e4290d5507xxxx
Manufacturer:
Apple
Model:
iBeacon

**Comment by adekloet** [comment]
Hi,Remove them by hand from the know_devices.yaml file. Restart and turn off auto discover in the esphome config and in the integration config.Hope this helps It can be picked up from neighbors or from passing by Apple tags. They can random change mac. Every Mac is a new device auto discovered. Could also be a rogue device nearby acting up. But 700 devices is a lot. I had more then 50 in one day and it's hard to tell where they come from. Add your know devices by hand to your config.
-------- Original message --------From: Musicman50 ***@***.***> Date: 10/11/2022  05:12  (GMT+01:00) To: custom-components/ble_monitor ***@***.***> Cc: Subscribed ***@***.***> Subject: Re: [custom-components/ble_monitor] Over 700 unknown iBeacon entries
  and counting from out of nowhere. (Issue #1045) 
I posted one of the devices in my very first post.
At This Point it's serious. CAN SOMEONE PLEASE PLEASE HELP.
I'VE NOW GOT OVER 700 Bluetooth devices and more each day (In Reality only have 7 devices. 5 Xiomai and 2 other BT devices)
This can't be "Rocket Science" How can I just delete these stealth devices???? And If it's in YAML then please tell me how before my whole system crashes...
I've only received an idea from one person.
HELP HELP HELP SOS !!!
Just one device here.. I've got over 700 more "Unknown Apple iBeacon devices if you want them..
Information from just one of many... Don;t know how or why they are here. I only have 7 devices total, but HA says I have 700 as of today.
Device:
sensor.ble_cypress_temperature_0438bxxxad01f1571e4290d5507xxxx
Manufacturer:
Apple
Model:
iBeacon

**Comment by albpara** [comment]
I have a similar issue… but never had more that 30 devices in the list luckily.

have you tried calling the `ble_monitor.cleanup_entries` service? Worked for me :)

**Comment by Musicman50** [comment]
> I have a similar issue… but never had more that 30 devices in the list luckily.
> 
> have you tried calling the `ble_monitor.cleanup_entries` service? Worked for me :)

Yes.. !!! Thank you .. I'll give this a try..
Sadly with all the devices I have installed, I have practically zero experience in YAML
IN fact I could not even find in since the newer version of HS was released.
But I'll give your suggestion a try and report back..

BTW: I think I found the cause, I think was an old Actel Cell Phone that kept on for running IOT apps. Always wondered why HS found it as an iPhone or iBeacon when it was an Old Andriod.

**Comment by Musicman50** [comment]
> have you tried calling the `ble_monitor.cleanup_entries` service? Worked for me :)

YES !!! You sir are a Blessings !!
Simply pasted your link under services and it magically deleted some 600 entries..
And I don't even know how it did that. But grateful

**However Now still some 17 devices and 122 entities left..**
Any suggestions?? Someone also said goto YAML and manually delete??
How do I do that?
Thank you so very much

![image](https://user-images.githubusercontent.com/53410267/201493262-92b57f48-76be-4fd9-bbce-e255a8769cb5.png)

**Comment by albpara** [comment]
Nice to hear that it worked for you!! I discovered that just a couple of weeks ago.

I don’t think that discovered entities are added automatically to any yaml file, I am not an expert in HA but that don’t usually work like that.

I am not sure what you could try afterwards, maybe manually disabling the entities and calling that service another time could do the trick

**Comment by Musicman50** [comment]
> have you tried calling the `ble_monitor.cleanup_entries` service? Worked for me :)

SUCCESS !!!  THANK YOU SIR !!!
I manually deleted the remaining 10 Apple iBeacon devices.. And then ran your Cleanup utility. All gone now..
Now 7 Devices and 42 Entities..

QUESTION: Should I dare to turn back on "Discover New Devices and Sensors" in the BLE configuration ? As presently the only way it stopped populating was when it was always on.

**Comment by albpara** [comment]
> > have you tried calling the `ble_monitor.cleanup_entries` service? Worked for me :)
> 
> SUCCESS !!! THANK YOU SIR !!! I manually deleted the remaining 10 Apple iBeacon devices.. And then ran your Cleanup utility. All gone now.. Now 7 Devices and 42 Entities..
> 
> QUESTION: Should I dare to turn back on "Discover New Devices and Sensors" in the BLE configuration ? As presently the only way it stopped populating was when it was always on.

Even with that option disabled… bluetooth devices keep appearing in my HA but now that you know how to get rid of those extra devices, you could try!

**Comment by Musicman50** [comment]
> I am not sure what you could try afterwards, maybe manually disabling the entities and calling that service another time could do the trick

Yeah I think I'll leave the Auto Discovery off for the time being. 
When I get a little more brave i'll try looking at what YAML file keeps that data. As I'm not very comfortable in that area yet. And Thank again..

**Comment by Musicman50** [comment]
Resolved Thanks to everyone's help !!

**Comment by Stooovie** [comment]
Same. 657 iBeacon devices. Running the cleanup service didn't fix the issue.
