### ISSUE TITLE
3x LYWSD03MMC with status Unavailable

### ISSUE THREAD

**Issue by pwlgrzs** [custom-components/ble_monitor#160]
After migrating to new integration 3 of my LYWSD03MMC are continously getting Unavailable status. Entities present correct values for some time just to got Unavailable and then eventually return after random period of time. 

They're also in Unavailabe state after any HASS restart, is this expected? They could just return last known value given the fact it takes a bit to refresh.

**Comment by Ernst79** [comment]
Please tell us the version you are using, beta or none-beta? Are the sensors close to the machine running Bluetooth. What are the RSSI values?

Sensors are always unavailable after a restart, but should appear after the time that is set in the period option. This is expected behavior (we have plans to implement restoring the state upon restart in a later version, but we (@Magalex2x14) first focus on other issues)

**Comment by pwlgrzs** [comment]
@Ernst79 I am using version 0.8.1, I am not seeing beta notice anywhere. One is few meters away, other 2 are 1-2m away from BT dongle. Dongle is working because I have another integration for Xiaomi weight and that one does work.
I cannot see RSSI values at the moment since after another restart they're still unavailable.

**Comment by Ernst79** [comment]
Two integrations that both use Bluetooth can cause issues like you describe. The following text from the FAQ explains the problem. 

**Conflicts with other components using the same BT interface**
Since our component uses a special operating mode of the HCI interface and works with a continuous data stream, conflicts with other software using the same HCI interface are possible. The conflict is caused by the fact that another component can switch the HCI interface to a different operating mode, thereby stopping the reception of data. Or our component may lead to malfunctioning of another component. A reliable, but not the only way out of this situation (apart from the refusal to use one component in favor of another) can be the use of two BT-interfaces (one for our component, the second, for example, for the tracker). Work is underway to find other solutions to such situations...

You can try to see if this is your issue by disabling the Xiaomi Weight integration temporarily and check if you still have issues afterwards. If not, the only solution is to use a second BT dongle. If you still have issues, turn on debug logging and post the logs here.

**Comment by lkobylski** [comment]
I have a similar issue with LYWSD03MMC.
After HA restart it receive data only for 20 minutes and stops.

I paste the log
`Logger: homeassistant
Source: custom_components/ble_monitor/aioblescan_ext.py:578
First occurred: 14:56:56 (9 occurrences)
Last logged: 15:11:38

Error doing job: Fatal error: protocol.data_received() call failed.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/asyncio/selector_events.py", line 860, in _read_ready__data_received
    self._protocol.data_received(data)
  File "/config/custom_components/ble_monitor/aioblescan_ext.py", line 1481, in data_received
    extra_data=ev.decode(packet)
  File "/config/custom_components/ble_monitor/aioblescan_ext.py", line 1087, in decode
    data=ev.decode(data)
  File "/config/custom_components/ble_monitor/aioblescan_ext.py", line 1133, in decode
    data = ev.decode(data)
  File "/config/custom_components/ble_monitor/aioblescan_ext.py", line 773, in decode
    data = field.decode(data)
  File "/config/custom_components/ble_monitor/aioblescan_ext.py", line 1158, in decode
    data=ad.decode(data)
  File "/config/custom_components/ble_monitor/aioblescan_ext.py", line 1348, in decode
    val.decode(data[:length.val-len(type)])
  File "/config/custom_components/ble_monitor/aioblescan_ext.py", line 612, in decode
    data=mynbyte.decode(data)
  File "/config/custom_components/ble_monitor/aioblescan_ext.py", line 578, in decode
    self.val=unpack(">%ds"%self.length,data[:self.length])[0][::-1]
struct.error: unpack requires a buffer of 16 bytes`

**Comment by Magalex2x14** [comment]
@lkobylski thanks for the report. There will be a fix in the next beta version (day / two).

**Comment by Magalex2x14** [comment]
@lkobylski [0.8.4-beta](https://github.com/custom-components/ble_monitor/releases/tag/0.8.4-beta) with fix has been released

**Comment by lkobylski** [comment]
Thank you a lot. Now it's working much better! 👍   
But I still see some errors logs. I'm not sure is relevant.

But I still see tome errors logs. I'm not sure is relevant.

```
Logger: root
Source: custom_components/ble_monitor/__init__.py:326
First occurred: 26 November 2020, 12:41:59 (624 occurrences)
Last logged: 10:58:14

Uncaught thread exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/config/custom_components/ble_monitor/__init__.py", line 326, in run
    self._event_loop.run_until_complete(btctrl[hci].send_scan_request(self._active))
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 614, in run_until_complete
    raise RuntimeError('Event loop stopped before Future completed.')
RuntimeError: Event loop stopped before Future completed.
```
  

```
Error doing job: Fatal error: protocol.data_received() call failed.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/asyncio/selector_events.py", line 860, in _read_ready__data_received
    self._protocol.data_received(data)
  File "/config/custom_components/ble_monitor/aioblescan_ext.py", line 1484, in data_received
    extra_data=ev.decode(packet)
  File "/config/custom_components/ble_monitor/aioblescan_ext.py", line 1088, in decode
    data=ev.decode(data)
  File "/config/custom_components/ble_monitor/aioblescan_ext.py", line 1134, in decode
    data = ev.decode(data)
  File "/config/custom_components/ble_monitor/aioblescan_ext.py", line 774, in decode
    data = field.decode(data)
  File "/config/custom_components/ble_monitor/aioblescan_ext.py", line 1159, in decode
    data=ad.decode(data)
  File "/config/custom_components/ble_monitor/aioblescan_ext.py", line 1349, in decode
    val.decode(data[:length.val-len(type)])
  File "/config/custom_components/ble_monitor/aioblescan_ext.py", line 612, in decode
    data=mynbyte.decode(data)
  File "/config/custom_components/ble_monitor/aioblescan_ext.py", line 578, in decode
    self.val=unpack(">%ds"%self.length,data[:self.length])[0][::-1]
struct.error: unpack requires a buffer of 4 bytes
```

**Comment by Magalex2x14** [comment]
Please reinstall 0.8.4-beta with HACS. Some changes have been made recently.
But the first error [is alarming](https://github.com/custom-components/ble_monitor/issues/167#issuecomment-734712422)... Try power off the host for a while and powering it back on.

**Comment by pwlgrzs** [comment]
Hello, I got that issue gone by flashing ATC firmware onto sensors. I think there could have been issue with the keys.

**Comment by Magalex2x14** [comment]
Since @pwlgrzs' problem has been solved, and @lkobylski's problem is related to another issue, I close this.
