### ISSUE TITLE
Inkbird IBT-2X - MAC address doesn't match data

### ISSUE THREAD

**Issue by ThePirat91** [custom-components/ble_monitor#629]
Hello guys,
I'm trying to integrate an Inkbird IBT-2X but unfortunately I'm not getting it.
I actually got some strange errors (for me, at least) on HA logs every every second (I am on log's DEBUG mode) from the component; see below.

```
2022-01-16 10:53:17 DEBUG (Thread-4) [custom_components.ble_monitor.ble_parser.inkbird] Inkbird MAC address doesn't match data MAC address. Data: 0fff0100000062000000b524ca00ffff
2022-01-16 10:53:18 DEBUG (Thread-4) [custom_components.ble_monitor.ble_parser.inkbird] Inkbird MAC address doesn't match data MAC address. Data: 0fff0100000062000000b524ca00ffff
2022-01-16 10:53:18 DEBUG (Thread-4) [custom_components.ble_monitor.ble_parser.inkbird] Inkbird MAC address doesn't match data MAC address. Data: 0fff0100000062000000b524ca00ffff
2022-01-16 10:53:19 DEBUG (Thread-4) [custom_components.ble_monitor.ble_parser.inkbird] Inkbird MAC address doesn't match data MAC address. Data: 0fff0100000062000000b524ca00ffff
2022-01-16 10:53:20 DEBUG (Thread-4) [custom_components.ble_monitor.ble_parser.inkbird] Inkbird MAC address doesn't match data MAC address. Data: 0fff0100000062000000b524ca00ffff
2022-01-16 10:53:21 DEBUG (Thread-4) [custom_components.ble_monitor.ble_parser.inkbird] Inkbird MAC address doesn't match data MAC address. Data: 0fff0200000062000000b5249700ffff
2022-01-16 10:53:22 DEBUG (Thread-4) [custom_components.ble_monitor.ble_parser.inkbird] Inkbird MAC address doesn't match data MAC address. Data: 0fff0100000062000000b524ca00ffff
2022-01-16 10:53:23 DEBUG (Thread-4) [custom_components.ble_monitor.ble_parser.inkbird] Inkbird MAC address doesn't match data MAC address. Data: 0fff0100000062000000b524ca00ffff
2022-01-16 10:53:24 DEBUG (Thread-4) [custom_components.ble_monitor.ble_parser.inkbird] Inkbird MAC address doesn't match data MAC address. Data: 0fff0100000062000000b524ca00ffff
2022-01-16 10:53:24 DEBUG (Thread-4) [custom_components.ble_monitor.ble_parser.inkbird] Inkbird MAC address doesn't match data MAC address. Data: 0fff0100000062000000b524ca00ffff
2022-01-16 10:53:25 DEBUG (Thread-4) [custom_components.ble_monitor.ble_parser.inkbird] Inkbird MAC address doesn't match data MAC address. Data: 0fff0100000062000000b524cb00ffff
2022-01-16 10:53:26 DEBUG (Thread-4) [custom_components.ble_monitor.ble_parser.inkbird] Inkbird MAC address doesn't match data MAC address. Data: 0fff0100000062000000b524ca00ffff
2022-01-16 10:53:27 DEBUG (Thread-4) [custom_components.ble_monitor.ble_parser.inkbird] Inkbird MAC address doesn't match data MAC address. Data: 0fff0100000062000000b524ca00ffff
2022-01-16 10:53:28 DEBUG (Thread-4) [custom_components.ble_monitor.ble_parser.inkbird] Inkbird MAC address doesn't match data MAC address. Data: 0fff0100000062000000b524ca00ffff
2022-01-16 10:53:29 DEBUG (Thread-4) [custom_components.ble_monitor.ble_parser.inkbird] Inkbird MAC address doesn't match data MAC address. Data: 0fff0100000062000000b524ca00ffff
```

Take a look below for the sensor informations

![Screenshot_20220116-102945808](https://user-images.githubusercontent.com/17300013/149655079-7df9a4f7-02d2-4152-8ad7-dbbbd070bb87.jpg)
![Screenshot_20220116-102951225](https://user-images.githubusercontent.com/17300013/149655080-265373d9-e315-42e7-8d9c-71ddb39332ca.jpg)

Thanks for your help!

**Comment by Ernst79** [comment]
Thanks for reportinh. ll look into it asap.

**Comment by Ernst79** [comment]
I found the issue, your BLE advertisements have the MAC in reversed order, per two characters. Other sensors have the MAC in normal order. I will create a fix for it.

**Comment by Ernst79** [comment]
Please try 7.1.0, should be fixed.

**Comment by ThePirat91** [comment]
Hello and thanks for your help.
Sorry to inform you that 7.1.0 is not working for me.
The error is changed but HA can't still receive the IBT data

![image](https://user-images.githubusercontent.com/17300013/150634276-28e758ae-30d5-4f42-a447-db3d01a984f8.png)

I am using yaml and not the gui integration
```
bt_interface: '.......'
decimals: 1
period: 120
log_spikes: False
use_median: False
active_scan: False
# report_unknown: True
discovery: False
devices:
  - mac: '24:B5:00:00:00:62'
    name: 'Inkbird IBT-2X'
```

Thank you

**Comment by Ernst79** [comment]
Fixed in 7.2.1
